name: Auto-merge

on:
  pull_request:
    types: [opened, ready_for_review, synchronize]
  check_suite:
    types: [completed]

jobs:
  auto-merge:
    name: Merge when CI is green
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false || github.event_name == 'check_suite'

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Enable auto-merge (squash)
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
